//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameNo { get; set; }
        public string GameTime { get; set; }
        public string GameDate { get; set; }
        public string GameVenue { get; set; }
        public Nullable<decimal> CourtFees { get; set; }
        public Nullable<int> WhoPaid { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
